In [1]:
import numpy as np

## Escalar

In [2]:
x = np.array(42)
print(x.shape)
print(x.ndim)

()
0


## Vector


In [3]:
x = np.array([42,23,453,21,32,1,3,7])
print("")
print(x.shape)
print(x.ndim)


(8,)
1


## Matriz

In [4]:
x = np.array([[42,23,453],
             [34,343,24]])
print(x.shape)
print(x.ndim)

(2, 3)
2


## Tensor

In [5]:
x = np.array([[[42,23,453],
             [34,343,24]],
             [[42,23,453],
             [34,343,24]],
             [[42,23,453],
             [34,343,24]],
             [[42,23,453],
             [34,343,24]]])
print(x.shape)
print(x.ndim)

(4, 2, 3)
3


## Reshape

In [6]:
x = np.array([[0,1],
             [2,3],
             [4,5],
             [6,7]])
print(x.shape)

(4, 2)


## Reshape unidimensional

In [7]:
x_reshape = x.reshape(8,1)
print(x_reshape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


## Reshape bidimensional

In [8]:
x_reshape = x.reshape(2,4)
print(x_reshape)

[[0 1 2 3]
 [4 5 6 7]]


## Transpuesta de la matriz

In [9]:
x_transpose = np.transpose(x)
print(x_transpose)
print(x.T)

[[0 2 4 6]
 [1 3 5 7]]
[[0 2 4 6]
 [1 3 5 7]]
